### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by richardciolek** [HCMID/plinius#12]
![](http://www.homermultitext.org/iipsrv?OBJ=IIP,1.0&FIF=/project/homer/pyramidal/deepzoom/bamberg/sbb104imgs/v1/sbb00000104_00222.tif&RGN=0.8290,0.5365,0.08300,0.03439&wID=5000&CVT=JPEG)

Folio 109 Verso

**Comment by michaelraheb** [comment]
Looks like "ex omnibus."
